name: Doc Generator

on:
  workflow_run:
    workflows: ["PHPUnit Test"]
    types:
      - completed
jobs:
  laravel-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: PHP 8.*
    env:
      DB_CONNECTION: mysql
      DB_DATABASE: test_database
      DB_USERNAME: root
    services:
      mysql:
        image: mariadb:10.5
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test_database
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install PHP versions
        uses: shivammathur/setup-php@v2
        with:
          extensions: mbstring, dom, fileinfo,pdo_sqlite,sqlite
          coverage: xdebug
          php-version: "8.1"
      - name: Get Composer Cache Directory 2
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        id: actions-cache
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Cache PHP dependencies
        uses: actions/cache@v2
        id: vendor-cache
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

      - name: Copy .env
        run: php -r "file_exists('.env.example') && copy('.env.example', '.env');" && chmod 777 .env.example && chmod 777 .env

      - name: Install Dependencies
        run: composer install -q --no-progress --prefer-dist --optimize-autoloader

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache database

      - name: App Key
        run: php artisan key:generate

      - name: Generate Scribe Documentation 📚
        run: php artisan scribe:generate

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
