name: PHPUnit Test

on:
  workflow_run:
    workflows: ["Fix styling"]
    types:
      - completed
jobs:
  laravel-test:
    runs-on: ubuntu-latest
    name: PHP 8.*
    env:
      DB_CONNECTION: mysql
      DB_DATABASE: dory8752_kasir
      DB_USERNAME: root
      DB2_CONNECTION: mysql2
      DB2_DATABASE: dory8752_from_local
      DB2_USERNAME: root
      SHOPEE_PARTNER_ID: 123456
      SHOPEE_SECRET: "TESTING_TOKEN"
      SHOPEE_BASE_URL: "https://partner.shopeemobile.com"
    services:
      mysql:
        image: mariadb:10.5
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: dory8752_jkt
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Create 2nd Database
        run: mysql --host 127.0.0.1 --port 3306 -uroot -e "CREATE DATABASE IF NOT EXISTS dory8752_from_local;"
      - name: Verify dory8752_from_local DB exists
        run: mysql --host 127.0.0.1 --port 3306 -uroot -e "SHOW DATABASES LIKE 'dory8752_from_local'"

      - name: Install PHP versions
        uses: shivammathur/setup-php@v2
        with:
          extensions: mbstring, dom, fileinfo,pdo_sqlite,sqlite
          coverage: xdebug
          php-version: "8.1"
      - name: Get Composer Cache Directory 2
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        id: actions-cache
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Cache PHP dependencies
        uses: actions/cache@v2
        id: vendor-cache
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

      - name: Copy .env
        run: php -r "file_exists('.env.example') && copy('.env.example', '.env');" && chmod 777 .env.example && chmod 777 .env

      - name: Install Dependencies
        run: composer install -q --no-progress --prefer-dist --optimize-autoloader

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache database

      - name: Run PHPUnit Test
        run: XDEBUG_MODE=coverage ./vendor/bin/phpunit --testdox
